[asyncapi-idea-plugin]: direct call instead of reference in AsyncAPISchemaReferencesCollector::collectFiles. Because of:
java.lang.NoSuchMethodError: 'void kotlin.jvm.internal.FunctionReferenceImpl.<init>(int, java.lang.Object, java.lang.Class, java.lang.String, java.lang.String, int)'
	at com.asyncapi.plugin.idea._core.AsyncAPISchemaReferencesCollector$collectFiles$1$2.<init>(AsyncAPISchemaReferencesCollector.kt)